### ISSUE TITLE
Docker does not build

### ISSUE THREAD

**Issue by Hailot** [ahmadrosid/pdfpintar#11]
When running `docker-compose up -d` the command fails
<img width="1204" alt="Screenshot 2023-10-21 at 09 24 18" src="https://github.com/ahmadrosid/pdfpintar/assets/13494687/fa146934-0d51-44a4-a4ba-c83c3c1b64cc">

**Comment by ahmadrosid** [comment]
HI @Hailot have you try to run `ziggy:generate`?

```bash
php artisan ziggy:generate
```

**Comment by Hailot** [comment]
@ahmadrosid Would you add that to the dockerfile ? 

Since the container isn't running I can't run that command manually

**Comment by ahmadrosid** [comment]
Yeah, feel free to open PR I am not available at the moment.

**Comment by spencerwongfeilong** [comment]
Hello

It's still not building after the ziggy:generate has been added to the dockerfile.

![image](https://github.com/ahmadrosid/pdfpintar/assets/127573355/2851c958-2767-4d4a-9db2-5d8527a548a7)

**Comment by yo-mike** [comment]
Hi @spencerwongfeilong -

I was able to get this working using Laravel Sail: https://github.com/ahmadrosid/pdfpintar/compare/main...yo-mike:pdfpintar:main

This uses Laravel Sail and compiles the libphp_pdf.so file from source. I'm also using another pgvector layer, which I just had in a previous sail project.

@ahmadrosid -- thanks for this project. It really is beautiful!

**Comment by arndvs** [comment]
I'm also unable to build in docker with the ```php artisan ziggy:generate```

@yo-mike, I tried to build using your sail fork, but an into this issue in the build:

![image](https://github.com/ahmadrosid/pdfpintar/assets/108478438/314cfa6b-dbe8-43fd-86c8-d8a5206969b1)

I'm not familuar with building in sail. Do I need to do anything additional to running the ```docker-compose up -d```?

**Comment by ahmadrosid** [comment]
Hi @arndvs what is the problem with Dockerfile from the source could you give me the error log for that?

**Comment by spencerwongfeilong** [comment]
> Hi @arndvs what is the problem with Dockerfile from the source could you give me the error log for that?

This is the error that i gotten

![image](https://github.com/ahmadrosid/pdfpintar/assets/127573355/4e74d146-c078-4b3e-aa5e-8182898ceee2)

**Comment by ahmadrosid** [comment]
Hi @spencerwongfeilong looks like it problem installing node-canvas package on windows. Try to follow the installation here: https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

**Comment by spencerwongfeilong** [comment]
> Hi @spencerwongfeilong, it looks like there is a problem installing the node-canvas package on Windows. Try following the installation instructions here: https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

Hello. I am on Ubuntu.

**Comment by ahmadrosid** [comment]
Try this for ubuntu: https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems

**Comment by spencerwongfeilong** [comment]
> Try this for ubuntu: https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems

Hello. Still not able to build after installing canvas. 

root@xeonubuntu:/home/CONTAINERS/pdfpintar# docker-compose up -d
Building server
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon   11.5MB
Step 1/16 : FROM node as builder
 ---> d7eb1d080096
Step 2/16 : RUN npm install --global pnpm
 ---> Using cache
 ---> dc12ca338e46
Step 3/16 : WORKDIR /app
 ---> Using cache
 ---> 2f49d279ea57
Step 4/16 : COPY . .
 ---> Using cache
 ---> 856306410084
Step 5/16 : RUN pnpm install
 ---> Using cache
 ---> 4b82bf8f31c6
Step 6/16 : RUN pnpm run build
 ---> Running in 8258cfe69f0c

> @ build /app
> tsc && vite build && vite build --ssr

resources/js/ssr.tsx(5,19): error TS2307: Cannot find module '../../vendor/tightenco/ziggy/dist/index.m' or its corresponding type declarations.
 ELIFECYCLE  Command failed with exit code 2.
The command '/bin/sh -c pnpm run build' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed
root@xeonubuntu:/home/CONTAINERS/pdfpintar#

**Comment by ahmadrosid** [comment]
Hi @spencerwongfeilong try to update your source code with this new changes: https://github.com/ahmadrosid/pdfpintar/pull/13

**Comment by spencerwongfeilong** [comment]
> Hi @spencerwongfeilong try to update your source code with this new changes: #13

Hi. The progress got further but still did not build. 

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 11.00s
vite v4.3.6 building SSR bundle for production...
transforming...
✓ 19 modules transformed.
✓ built in 1.31s
[vite:load-fallback] Could not load /app/vendor/tightenco/ziggy (imported by resources/js/ssr.tsx): ENOENT: no such file or directory, open '/app/vendor/tightenco/ziggy'
error during build:
Error: Could not load /app/vendor/tightenco/ziggy (imported by resources/js/ssr.tsx): ENOENT: no such file or directory, open '/app/vendor/tightenco/ziggy'
 ELIFECYCLE  Command failed with exit code 1.
The command '/bin/sh -c pnpm run build' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed
administrator@xeonubuntu:/home/CONTAINERS/pdfpintar$

**Comment by ahmadrosid** [comment]
Hi all, sorry for the very, very late response. I've updated the Dockerfile and removed the php-pdf library. Now, you should be able to run `docker-compose up` with no issue.

**Comment by spencerwongfeilong** [comment]
Hello it does build successfully. But accessing the browser on 9000, in my case 9123, the web server does not load. It seems that the web server is not connected to the pgvector database. 

Could you share your env?

**Comment by ahmadrosid** [comment]
Here's my env

```bash
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:wx+4HYSDe9biSPaqHfWdo2cAV5X1u7f4pwuglbG2Sjk=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=pgsql
DB_HOST=pgvector
DB_PORT=5432
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="${PUSHER_HOST}"
VITE_PUSHER_PORT="${PUSHER_PORT}"
VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

BIN_PDF_TO_TEXT=/usr/bin/pdftotext
BIN_PDF_INFO=/usr/bin/pdfinfo

OPENAI_API_KEY=...
```

**Comment by spencerwongfeilong** [comment]
Hello. Still no dice. Other than docker compose up. Do we need more configuration?

**Comment by ahmadrosid** [comment]
Yeah that should be enough. It will run on 
```
http://localhost
```
If you are trying on other device you should be using your IP no need to define port just the ip.

**Comment by spencerwongfeilong** [comment]
Hello i still can't access the front end. 

Here are my observations. 
I think you made a mistake in the file path for the database directory. 
database:/var/lib/pgsql/data:rw
It should be database:/var/lib/posgresql/data:rw i think? 

Also when i manually set my file path on the host for the posgresql data path, i saw in winscp that the directory owner is Ixd instead of my own user account (administrator). Not sure if i am doing it correctly.

**Comment by ahmadrosid** [comment]
Hi everyone! I just wanted to give you all an update: this project has been refactored to be simpler. There are no more complicated steps to install. Please check the new readme for installation steps. 🙏

**Comment by ahmadrosid** [comment]
I am closing this issue now.
