### ISSUE TITLE
Inertia Js past commits missing

### ISSUE THREAD

**Issue by kudjieRaymond** [ahmadrosid/pdfpintar#15]
Hello I understand that you are no more  using inertiajs but I can seem to find all the past commits about inertiajs.

**Comment by ahmadrosid** [comment]
Hi @kudjieRaymond 

Sorry, I completely rewrote this app from the ground up. Any code related to Innertia has been deleted.
However, if you need to work with the previous version, you can access it using this tag: https://github.com/ahmadrosid/pdfpintar/releases/tag/v1.0.0

**Comment by kudjieRaymond** [comment]
alright. noted.
Thank you @ahmadrosid
