### ISSUE TITLE
Tidak ada respon dari open AI ketika klik "send" atau menjalankan getAssistantResponse

### ISSUE THREAD

**Issue by mlbbsage** [ahmadrosid/pdfpintar#17]
saat ini aplikasi sudah berhasil saya instal di localhost,

namun ketika saya memasukkan pertanyaan terkait isi pdf, saya tidak mendapatkan respon apapun,
ketika saya cek $message_content pada function getAssistantResponse, nilai yang dikembalikan selalu kosong dan tidak menampilkan apapun,
mohon bantuannya apakah saya ada salah langkah atau ada langkah yg terlewat?

**Comment by mlbbsage** [comment]
baik mas terimakasih, infonya

**Comment by ahmadrosid** [comment]
Sudah resolve belum issuenya @mlbbsage ?
